"""Custom exceptions generated by the application"""

class MessageIsTooLong(Exception):
    """The input message is too long"""
    pass

class TerminatedByOtherGetUpdates(Exception):
    pass

class TooManyRequests(Exception):
    pass
